In [5]:
import numpy

In [6]:
numpy.__version__

'2.3.4'

In [7]:
import numpy as np

In [8]:
np.__version__

'2.3.4'

In [9]:
arr = [1,2,3,4,5]
arr

[1, 2, 3, 4, 5]

In [10]:
narr = np.array(arr)
narr

array([1, 2, 3, 4, 5])

In [11]:
arr_2d =[[1,2,3],[4,5,6],[7,8,9]] 
arr_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
narr_2d = np.array(arr_2d)
narr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(10,15,2)

array([10, 12, 14])

In [20]:
np.zeros([3,4,5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [25]:
np.ones([3,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [26]:
np.linspace(start=10, stop=20 , num=5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [27]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
import numpy as np

In [5]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
from numpy import random

In [9]:
np.random.rand(10,2)

array([[0.37569744, 0.82810532],
       [0.29569346, 0.40880942],
       [0.03858357, 0.24208964],
       [0.27706137, 0.98802071],
       [0.57081409, 0.2058664 ],
       [0.35592826, 0.6436117 ],
       [0.14339203, 0.50013819],
       [0.44185626, 0.59251822],
       [0.41988119, 0.94739075],
       [0.60022244, 0.56200387]])

In [20]:
np.random.randn()

-1.1287676426640874

In [29]:
 ad = np.random.randint(10 , 20, size=[2,4,6])

In [30]:
ad.shape

(2, 4, 6)

In [35]:
 ad_2d = ad.reshape(6, 8)

In [33]:
ad

array([[[16, 14, 13, 19, 15, 17],
        [11, 17, 18, 10, 14, 16],
        [17, 14, 10, 13, 18, 14],
        [17, 14, 19, 14, 13, 11]],

       [[16, 14, 16, 10, 13, 19],
        [18, 16, 18, 15, 10, 15],
        [18, 19, 15, 17, 12, 17],
        [12, 16, 14, 14, 19, 12]]], dtype=int32)

In [36]:
ad_2d

array([[16, 14, 13, 19, 15, 17, 11, 17],
       [18, 10, 14, 16, 17, 14, 10, 13],
       [18, 14, 17, 14, 19, 14, 13, 11],
       [16, 14, 16, 10, 13, 19, 18, 16],
       [18, 15, 10, 15, 18, 19, 15, 17],
       [12, 17, 12, 16, 14, 14, 19, 12]], dtype=int32)

In [38]:
ad_2d.min()

np.int32(10)

In [1]:
import numpy as np

In [11]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
arr[0]

np.int64(0)

In [5]:
arr[-1]

np.int64(9)

In [9]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [10]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
arr[7:18]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [13]:
arr2 = arr[7:17]
arr2

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [14]:
arr2[4] = 99
arr2

array([ 7,  8,  9, 10, 99, 12, 13, 14, 15, 16])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 99, 12, 13, 14, 15, 16,
       17, 18, 19])

In [1]:
import numpy as np

In [2]:
matrix = np.array([[1,2,3,4], [10,20,30,40],[100,200,300,400],[1000,2000,3000,4000]])
matrix

array([[   1,    2,    3,    4],
       [  10,   20,   30,   40],
       [ 100,  200,  300,  400],
       [1000, 2000, 3000, 4000]])

In [9]:
new_array = []
rows = matrix[1:3]
for row in rows:
    new_array.append(row[1:3])
new_array

[array([20, 30]), array([200, 300])]

In [10]:
matrix[1:3, 1:3]

array([[ 20,  30],
       [200, 300]])

In [11]:
matrix[:,1:3]

array([[   2,    3],
       [  20,   30],
       [ 200,  300],
       [2000, 3000]])

In [3]:
third_row = matrix[2]
third_row

array([100, 200, 300, 400])

In [4]:
third_row[2]

np.int64(300)

In [8]:
matrix[2,2]

np.int64(300)

In [1]:
import numpy as np

In [3]:
arr = [23,5,4,8,7,5,9,41,21,54,63,25]

In [4]:
ans = []
for i in arr:
    if i > 7:
        ans.append(i)
ans

[23, 8, 9, 41, 21, 54, 63, 25]

In [5]:
narr = np.array(arr)
narr

array([23,  5,  4,  8,  7,  5,  9, 41, 21, 54, 63, 25])

In [7]:
bool_arr = narr > 9

In [8]:
narr[bool_arr]

array([23, 41, 21, 54, 63, 25])

In [11]:
narr = np.arange(20)
narr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
narr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [13]:
result = []
for x in [1, 2, 3, 4, 5]:
    result.append(x ** 2)
print(result)

[1, 4, 9, 16, 25]


In [14]:
arr = np.array([1, 2, 3, 4, 5])
result = np.square(arr)
print(result)

[ 1  4  9 16 25]


In [1]:
import numpy as np